### ISSUE TITLE
Check for max path length

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.GitRepository#11]
Check that all file paths are not longer than a configurable length

**Comment by GusAV** [comment]
What's the file that handles this logic?

**Comment by pascalberger** [comment]
@GusAV Currently this addins checks for binary files which are not tracked by Git LFS. This is done in [GitRepositoryIssuesProvider.cs](https://github.com/cake-contrib/Cake.Issues.GitRepository/blob/develop/src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs#L65-L68). For this a similar check should be implemented which checks for path length and adds issues for files which have a too long path (see [here](https://github.com/cake-contrib/Cake.Issues.GitRepository/blob/develop/src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs#L116-L121) for an example how to create an issue).
Additionaly it requires additional parameter in [GitRepositoryIssuesSettings.cs](https://github.com/cake-contrib/Cake.Issues.GitRepository/blob/develop/src/Cake.Issues.GitRepository/GitRepositoryIssuesSettings.cs) to enable the check and define the max length for the check.

**Comment by GusAV** [comment]
Ok I think I understand. What is to be considered too long?

**Comment by pascalberger** [comment]
> @GusAV wrote:
> What is to be considered too long?

This should be a setting in `GitRepositoryIssuesSettings` so that the user can define what's too long. 

Another thing to consider is that only files which are part of the Git repository should be checked (e.g. files ignored by Git or not yet staged or commited should not be checked).
